"""Generate REPORT.md from the artifacts the pipeline leaves behind.

Kept separate from the pipeline so the write-up can be regenerated -- and
reworded -- without retraining anything.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from .config import CFG, Config

FIGURES = [
    ("univariate_effects.png", "Univariate separation between septic and non-septic admissions, FDR-controlled."),
    ("drift_psi.png", "Features that move most between the two hospital systems."),
    ("optuna_history.png", "Hyperparameter search, scored on clinical utility rather than AUROC."),
    ("importance.png", "Split gain versus TreeSHAP attribution for the tuned booster."),
    ("discrimination_test.png", "ROC and precision-recall on the held-out hospital A test set."),
    ("utility_test.png", "Normalised utility against threshold and against alert burden."),
    ("calibration_test.png", "Reliability before and after isotonic recalibration, on the held-out test split."),
    ("lead_time_test.png", "Hours of warning before clinical onset, for the admissions the model catches."),
    ("external_validation.png", "Internal test versus the unseen second hospital."),
]


def _read_csv(cfg: Config, name: str) -> pd.DataFrame | None:
    path = cfg.reports_dir / name
    return pd.read_csv(path) if path.exists() else None


def _table(df: pd.DataFrame, columns: list[str] | None = None, n: int = 10, floatfmt: str = ".4f") -> str:
    if df is None or df.empty:
        return "_not available_\n"
    view = df[columns] if columns else df
    return view.head(n).to_markdown(index=False, floatfmt=floatfmt) + "\n"


def write_report(cfg: Config = CFG) -> Path:
    cfg.ensure_dirs()
    metrics_path = cfg.reports_dir / "metrics.json"
    if not metrics_path.exists():
        raise FileNotFoundError("run the evaluate stage before generating the report")
    payload = json.loads(metrics_path.read_text())

    results = pd.DataFrame(payload["results"])
    test = results[results["split"] == "test"].set_index("model")
    external = results[results["split"] == "external"].set_index("model")

    splits = _read_csv(cfg, "split_summary.csv")
    screen = _read_csv(cfg, "univariate_screen.csv")
    missing = _read_csv(cfg, "missingness_tests.csv")
    inference = _read_csv(cfg, "logistic_inference.csv")
    signature = _read_csv(cfg, "sparse_signature.csv")
    shap_rank = _read_csv(cfg, "shap_ranking.csv")
    drift = _read_csv(cfg, "drift_report.csv")
    lead = pd.DataFrame(payload.get("lead_time", []))
    calibration = pd.DataFrame(payload.get("calibration", []))
    contributions = pd.DataFrame(payload.get("contributions", []))
    delong = pd.DataFrame(payload.get("delong", []))

    champion = test["utility"].idxmax()
    lines: list[str] = []
    add = lines.append

    add("# Early Sepsis Prediction — Results\n")
    add(
        "Generated by `sepsis evaluate`. Every number below comes from data the "
        "model in question never saw during fitting or tuning: hyperparameters and "
        "blend weights were selected on the validation split, the hospital A test "
        "split was scored once, and hospital B was untouched until this table.\n"
    )

    add("## Cohort\n")
    if splits is not None:
        cohort = splits.rename(columns={splits.columns[0]: "split"}).copy()
        for col in ("hours", "admissions", "septic_admissions"):
            if col in cohort.columns:
                cohort[col] = cohort[col].astype(int)
        add(cohort.to_markdown(index=False, floatfmt=".4f", intfmt=",") + "\n")

    add("## Headline results\n")
    cols = ["auroc", "auprc", "utility", "sensitivity", "precision", "alert_rate"]
    add("**Hospital A — held-out test**\n")
    add(test[cols].reset_index().to_markdown(index=False, floatfmt=".4f") + "\n")
    add("**Hospital B — external validation, never seen in any form**\n")
    add(external[cols].reset_index().to_markdown(index=False, floatfmt=".4f") + "\n")

    if "auroc_ci_low" in test.columns:
        row = test.loc[champion]
        add(
            f"Best model by clinical utility: **{champion}** — test AUROC "
            f"{row['auroc']:.3f} (95% CI {row['auroc_ci_low']:.3f}–{row['auroc_ci_high']:.3f}, "
            f"patient-level cluster bootstrap), normalised utility {row['utility']:.3f}. "
            f"On hospital B the same frozen model and threshold give AUROC "
            f"{external.loc[champion, 'auroc']:.3f} and utility "
            f"{external.loc[champion, 'utility']:.3f}.\n"
        )

    if not delong.empty:
        add("### Are the differences real?\n")
        add(
            "DeLong test for correlated ROC curves — the models score identical "
            "rows, so an unpaired comparison would be needlessly conservative.\n"
        )
        add(_table(delong, ["champion", "challenger", "auc_a", "auc_b", "diff", "z", "p_value"],
                   n=6, floatfmt=".3g"))

    trials = _read_csv(cfg, "optuna_trials.csv")
    if trials is not None and "xgboost" in test.index and "value" in trials.columns:
        best_cv = float(trials["value"].max())
        n_pruned = int((trials["state"] == "PRUNED").sum()) if "state" in trials else 0
        add("### What the search actually bought\n")
        add(
            f"The Optuna search ran {len(trials)} trials ({n_pruned} pruned) against "
            f"3-fold grouped cross-validation, reaching a best out-of-fold utility of "
            f"**{best_cv:.4f}**. The same configuration scores "
            f"**{test.loc['xgboost', 'utility']:.4f}** on the held-out test split.\n"
        )
        add(
            f"That {best_cv - float(test.loc['xgboost', 'utility']):+.4f} gap is selection "
            f"optimism, and it is expected: taking the maximum over {len(trials)} trials of a "
            f"noisy, piecewise-constant objective selects partly for luck. It is reported "
            f"rather than hidden because the CV number is the one that would be quoted if "
            f"nobody had held a test set back — which is exactly why one was held back.\n"
        )

    if not lead.empty:
        add("## What this looks like at the bedside\n")
        keep = [c for c in ["model", "detection_rate", "median_lead_time_h",
                            "false_alarm_rate_per_admission", "false_alarms_per_true_detection"]
                if c in lead.columns]
        add(_table(lead.reset_index(names="model") if "model" not in lead.columns else lead, keep, n=6, floatfmt=".3f"))
        add(
            "`detection_rate` counts a septic admission as caught only if the first "
            "alert lands *before* clinical onset; an alert raised after the team "
            "already suspected sepsis is not an early warning.\n"
        )

    add("## Statistical analysis\n")
    if screen is not None:
        n_sig = int(screen["significant"].sum())
        add(
            f"{n_sig} of {len(screen)} features separate septic from non-septic "
            f"admissions at FDR < 0.05 (Benjamini-Hochberg over Welch tests). Tests "
            f"are run on one summary value per admission, not per ICU hour: hours "
            f"within a stay are strongly autocorrelated, and treating them as "
            f"independent inflates significance by orders of magnitude.\n"
        )
        add(_table(screen, ["feature", "hedges_g", "univariate_auc", "p_welch", "q_welch"], n=12, floatfmt=".4g"))

    if missing is not None and not missing.empty:
        add("### Missingness is not noise\n")
        add(
            "Whether a lab was *ordered* — ignoring its value entirely — separates "
            "the groups on its own. That is why the feature matrix carries recency "
            "and ordering-intensity channels rather than imputing them away.\n"
        )
        add(_table(missing, ["channel", "order_rate_septic", "order_rate_control",
                             "auc_of_ordering", "q_value"], n=8, floatfmt=".4g"))

    if inference is not None:
        add("### Logistic regression, interpreted\n")
        add(
            "Refit without penalty on the collinearity-pruned matrix, because Wald "
            "standard errors do not apply to penalised coefficients. Odds ratios are "
            "per standard deviation of the feature.\n"
        )
        add(_table(inference, ["feature", "odds_ratio_per_sd", "or_ci_low", "or_ci_high",
                               "p_value", "q_value"], n=12, floatfmt=".4g"))

    if signature is not None:
        add(
            f"An elastic-net fit (L1-dominant) reduces the matrix to "
            f"**{len(signature)} non-zero coefficients** — a candidate short list for "
            f"a bedside score.\n"
        )
        add(_table(signature, ["feature", "coefficient", "odds_ratio_per_sd"], n=10))

    add("## Model behaviour\n")
    if not calibration.empty:
        add("### Calibration\n")
        add(
            "Class weighting buys ranking quality at the cost of the probability "
            "scale. Isotonic maps were fitted on validation and are scored here on "
            "the held-out test split — reporting them on validation would be "
            "circular, since in-sample isotonic ECE is 0 by construction. "
            "Discrimination is essentially unchanged while Brier and ECE move "
            "substantially.\n"
        )
        add(_table(calibration, ["model", "brier_raw", "brier_calibrated", "ece_raw",
                                 "ece_calibrated", "auroc_raw", "auroc_calibrated"], n=6))

    if not contributions.empty:
        add("### What each model contributes\n")
        add(
            "Blend weights were optimised against validation utility and then "
            "frozen. `marginal_contribution` is what the blend loses if that member "
            "is removed — a large weight with a small ablation cost means the member "
            "is redundant.\n"
        )
        add(_table(contributions, ["model", "weight", "utility_alone", "utility_without",
                                   "marginal_contribution"], n=6))

    if shap_rank is not None:
        add("### What drives the booster\n")
        add(_table(shap_rank, ["feature", "mean_abs_shap"], n=12))

    if drift is not None:
        add("### Cross-site shift\n")
        n_material = int((drift["psi"] > 0.25).sum())
        add(
            f"{n_material} of {len(drift)} features shift materially (PSI > 0.25) "
            f"between the two hospitals, and admission-level sepsis prevalence falls "
            f"from 8.8% to 5.7%. The external column in the headline table is the "
            f"cost of that shift, measured rather than assumed.\n"
        )
        add(_table(drift, ["feature", "psi", "missing_ref", "missing_cmp", "ks_stat"], n=10))

    add("## Figures\n")
    for name, caption in FIGURES:
        if (cfg.figures_dir / name).exists():
            add(f"**{caption}**\n")
            add(f"![{name}](figures/{name})\n")

    path = cfg.reports_dir / "REPORT.md"
    path.write_text("\n".join(lines))
    print(f"[report] wrote {path}", flush=True)
    return path
